### PR TITLE
Add jitpack.io compilation instructions

### PR DESCRIPTION
**Pull request by christiandeange**
While the repo is not yet available on Maven, you can still use jitpack.io to compile it through gradle

### CODE REVIEW

**Comment by tajchert** [comment]
I tried Jitpack.io yesterday but it doesn't recognize "android-MNC" as a target SDK - which is needed as there is not yet official "API 23" or so.

Log: https://jitpack.io/com/github/tajchert/nammu/0.1.0/build.log

Or maybe there is some workaround?

**Comment by tajchert** [comment]
Lets move discussion here https://github.com/tajchert/Nammu/issues/2 as it is more about whole targetSdkVersion thing and less related to this pull request.
Also will be easier to notice to new users of library than a comments on a pull request.

**Comment by jitpack-io** [comment]
Hi!
Installed android-MNC! Fixed the build:) 
https://jitpack.io/#tajchert/Nammu/0.1.0
For any issues just give us a shout. You might need to run gradle with --refresh-dependencies to get the new build.

**Comment by pelotasplus** [comment]
that's the spirit! thanks @jitpack-io :-)

**Comment by jitpack-io** [comment]
Welcome!:) Happy hacking!

**Comment by tajchert** [comment]
That was awesome @jitpack-io 
Thanks!

**Pull request merged**
